#!/usr/bin/env python
# This so-called "installer" just sets up symbolic links
# to the 3 subdirectories. Only needed on initial cloning.
from __future__ import print_function
import os
import subprocess

def printFailMessage():
    print("Symbolic links can not be built by this script.")
    print("You will need to manually make the following symbolic links to ")
    print("directories in this module:")
    print("<moodlehome>/question/type/coderunner -> coderunner")
    print("<moodlehome>/question/behaviour/adaptive_adapted_for_coderunner -> adaptive_adapted_for_coderunner")
    print("<moodlehome>/local/Twig -> Twig")

cwd = os.getcwd()
if "moodle/local/CodeRunner" not in cwd:
    print("WARNING: module appears not to have been installed in moodle/local")
    print ("as recommended.")
    printFailMessage()
else:
    try:

        searchString = "/moodle/local/CodeRunner"
        pos = cwd.index(searchString)
        basedir = cwd[0:pos]
        installdir = cwd[0:pos + len(searchString)]
        dirs = [("Twig", "moodle/local/Twig"),
		("coderunner", "moodle/question/type/coderunner"),
		("adaptive_adapted_for_coderunner", "moodle/question/behaviour/adaptive_adapted_for_coderunner")]

	for (src,dest) in dirs:
            if os.path.isdir("{0}/{1}".format(basedir, dest)):
	        continue  # Directory already exists
            if subprocess.call("ln -s {0}/{1} {2}/{3}".format(installdir, src, basedir, dest), shell=True) != 0:
                raise OSError("Failed to create symbolic link")

    except Exception as e:
	print("Exception when making symbolic links: " + str(e))
	printFailMessage()


