site_name: CodeRunner Documentation
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - toc.follow

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
